name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: PHP Unit Test
    strategy:
      matrix:
        php: ['8.2']
        wp: ['latest', '6.6']
    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
    with:
      php_version: ${{ matrix.php }}
      wp_version: ${{ matrix.wp }}

  lint:
    name: PHP Code Sniffer
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 8.2

  assets:
    name: Assets Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm packages
        run: npm install

      - name: Run JS & CSS lint
        run: npm run lint

      - name: Build Assets
        run: npm run build

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: always()
    needs: [test, lint, assets]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
